"""The wire format for webhook signatures, pinned against a vector the SERVER produced.

The signature is generated by the worker and verified here. Writing both halves from the same
understanding is how two sides agree with each other and disagree with reality, so the vector
below was emitted by the real `signWebhook` in the backend rather than recomputed here.
"""

import time

from singularity_grid import verify_pod_webhook

# Emitted by SGLCompute_Backend `signWebhook` (src/lib/pod-events.ts).
SECRET = "whsec_" + "a" * 48
BODY = '{"event":{"id":"e1","seq":7,"type":"pod.destroyed"}}'
TS = 1788000000
SIG = "t=1788000000,v1=367d429c4547093ae53a97b3bf5d8b62670e39676709fda0fb3748279dc71531"

# Evaluated as if it were moments after signing, so the age check is not what is under test.
NOW = TS + 5


def test_accepts_a_signature_the_server_actually_produced():
    assert verify_pod_webhook(BODY, SIG, SECRET, now=NOW) is True


def test_rejects_a_re_encoded_body():
    # Re-serialising JSON changes key order and spacing. A partner who parses then re-encodes
    # would fail to verify a genuine delivery and conclude our signatures are broken, so this
    # documents that the RAW bytes are what must be passed.
    import json

    reencoded = json.dumps(json.loads(BODY), indent=2)
    assert verify_pod_webhook(reencoded, SIG, SECRET, now=NOW) is False


def test_rejects_wrong_secret_and_tampered_body():
    assert verify_pod_webhook(BODY, SIG, "whsec_" + "b" * 48, now=NOW) is False
    assert verify_pod_webhook(BODY + " ", SIG, SECRET, now=NOW) is False


def test_rejects_a_genuine_signature_that_is_too_old():
    # The timestamp is inside the signed string, so an old capture cannot be replayed under a
    # fresh one — but only if the receiver enforces the window.
    assert verify_pod_webhook(BODY, SIG, SECRET, now=TS + 4000) is False
    assert verify_pod_webhook(BODY, SIG, SECRET, now=TS + 10) is True


def test_rejects_a_malformed_header_instead_of_raising():
    for bad in ["", "nonsense", "t=abc,v1=def", "t=1,v1=short", "v1=" + "a" * 64, None]:
        assert verify_pod_webhook(BODY, bad, SECRET, now=NOW) is False
